#!/usr/bin/env python3
"""Generate a checksum-locked SQL CTE from the complete NUH OU mapping JSON."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

FIELDS = (
    "organizational_unit",
    "organizational_unit_name",
    "department_grouping",
    "cluster_grouping",
    "moh_specialty_code",
    "moh_specialty_description",
)


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mapping", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    # Emit every mapping attribute as text so mixed values such as MOH code
    # 13 and "xx" have one portable VALUES-column type in Trino and PostgreSQL.
    return "'" + str(value).replace("'", "''") + "'"


def selected_records(document: dict) -> tuple[list[dict], str]:
    records = document.get("records")
    declared = document.get("source", {}).get("record_count")
    if not isinstance(records, list):
        raise ValueError("mapping JSON must contain a records array")
    selected = [{field: record.get(field) for field in FIELDS} for record in records]
    selected.sort(key=lambda record: str(record["organizational_unit"] or ""))
    ous = [str(record["organizational_unit"] or "").strip() for record in selected]
    if declared != 277 or len(selected) != 277 or len(set(ous)) != 277 or "" in ous:
        raise ValueError("declared, record, and unique nonblank OU counts must all be 277")
    canonical = json.dumps(selected, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return selected, hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def render(records: list[dict], checksum: str) -> str:
    values = []
    for record in records:
        values.append("    (" + ", ".join(sql_literal(record[field]) for field in FIELDS) + ")")
    columns = ", ".join(FIELDS)
    return (
        "-- Generated by scripts/generate_mapping_cte.py; do not edit.\n"
        f"-- mapping_count: {len(records)}\n"
        f"-- mapping_sha256: {checksum}\n"
        "nuh_mapping_meta (mapping_count, mapping_sha256) AS (\n"
        f"    VALUES ({len(records)}, '{checksum}')\n"
        "),\n"
        f"nuh_subspec_mapping ({columns}) AS (\n"
        "  VALUES\n" + ",\n".join(values) + "\n)\n"
    )


def main() -> int:
    args = arguments()
    try:
        document = json.loads(args.mapping.read_text(encoding="utf-8"))
        records, checksum = selected_records(document)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(render(records, checksum), encoding="utf-8")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"GENERATION FAILED: {exc}", file=sys.stderr)
        return 1
    print(json.dumps({"status": "PASSED", "mapping_count": len(records), "mapping_sha256": checksum, "output": str(args.output)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
